#!/usr/bin/env python

import argparse
import lxml.etree as etree


parser = argparse.ArgumentParser()
parser.add_argument("files", nargs='*', type=argparse.FileType('r'))

args = parser.parse_args()

for f in args.files:
    print(etree.tostring(etree.parse(f), pretty_print=True).decode("UTF-8"))
